mod two_sum;
mod average_salary_excluding_maximum_and_minimum;
mod min_partitions;
mod subrectangle_queries;
mod is_strictly_palindromic;
mod deepest_leaves_sum;
mod array_sign;
mod find_difference;
mod predict_party_victory;